name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    if: success()
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup hlint
      uses: haskell/actions/hlint-setup@v2
      with:
        version: "3.5"
    - name: Apply hlint
      run: |
        set -ex
        hlint .
  build:
    name : Build
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: stack build
  test-unit:
      name: Unit tests
      if: success()
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run unit tests
        run: stack test :unit
  test-integration:
      name: Integration tests
      if: success()
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run unit tests
        run: stack test :integration
