name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  style:
    name: Lint
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup hlint
      uses: haskell/actions/hlint-setup@v2
      with:
        version: "3.5"
    - name: Apply hlint
      run: |
        set -ex
        hlint .